name: riverpie
description: A tiny state management library for Flutter. Inspired by Riverpod.
version: 0.4.0
homepage: https://github.com/Tienisto/riverpie

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
