name: riverpie
description: A tiny state management library for Flutter. Inspired by Riverpod.
version: 0.8.0
repository: https://github.com/Tienisto/riverpie
topics:
  - state
  - provider
  - riverpod
  - framework

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
