name: refena_flutter
description: A state management library for Dart and Flutter. Inspired by Riverpod and async_redux.
version: 0.29.0
repository: https://github.com/refena/refena
topics:
  - state
  - provider
  - riverpod
  - framework
  - redux

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0
  refena: ^0.29.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
