name: refena_inspector_client
description: The client for the Refena Inspector.
version: 0.0.1
repository: https://github.com/refena/refena
topics:
  - refena

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
  refena: ^0.29.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
