name: refena_inspector
description: The inspector developer utility app for the Refena state management library.
version: 0.7.0
repository: https://github.com/refena/refena/tree/main/refena_inspector
issue_tracker: https://github.com/refena/refena/issues
topics:
  - refena
screenshots:
  - description: The Refena logo.
    path: resources/icon.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.1.0
  path: ^1.8.0
  refena: '>=0.35.0 <1.0.0'
  refena_flutter: '>=0.35.0 <1.0.0'
  refena_inspector_client: ^0.7.0
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
